# Generated by Django 2.1.2 on 2018-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('home', 'Home'), ('about', 'About')], default='home', max_length=5)),
                ('image', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Member', 'Member'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Vice President', 'Vice President'), ('President', 'President'), ('Former-Secretary', 'Former-Secretary'), ('Former-Treasurer', 'Former-Treasurer'), ('Former-Vice President', 'Former-Vice President'), ('Former-President', 'Former-President')], default='Member', max_length=25)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('restriction', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('registrar', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
